const fs = require('fs');
const path = require('path');
const et = require('elementtree');

const NETWORKS = require('./networks.json');

module.exports = function (context) {
    const projectRoot = context.opts.projectRoot;

    console.log("-----------------------------------------");
    console.log("AdMob MEDIATION SUITE..");
    console.log("-----------------------------------------");

    function getVar(varName) {
        try {
            const packageJsonPath = path.join(projectRoot, 'package.json');
            if (fs.existsSync(packageJsonPath)) {
                const packageData = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
                if (packageData.cordova &&
                    packageData.cordova.plugins &&
                    packageData.cordova.plugins['admob-mediation-suite'] &&
                    packageData.cordova.plugins['admob-mediation-suite'][varName]) {
                    return packageData.cordova.plugins['admob-mediation-suite'][varName];
                }
            }
        } catch (e) { /* ignore */ }

        try {
            const configPath = path.join(projectRoot, 'config.xml');
            if (fs.existsSync(configPath)) {
                const configRaw = fs.readFileSync(configPath).toString();
                const configXml = et.parse(configRaw);
                const root = configXml.getroot();

                const prefs = root.findall('preference');
                for (let i = 0; i < prefs.length; i++) {
                    if (prefs[i].get('name') === varName) {
                        return prefs[i].get('value');
                    }
                }

                const plugins = root.findall('plugin');
                for (let j = 0; j < plugins.length; j++) {
                    if (plugins[j].get('name') === 'admob-mediation-suite' || plugins[j].get('id') === 'admob-mediation-suite') {
                        const pluginVars = plugins[j].findall('variable');
                        for (let k = 0; k < pluginVars.length; k++) {
                            if (pluginVars[k].get('name') === varName) {
                                return pluginVars[k].get('value');
                            }
                        }
                    }
                }
            }
        } catch (e) { /* ignore */ }

        return '';
    }

    const enabledNetworks = NETWORKS.filter(net => {
        return getVar('ENABLE_' + net.key) === 'true';
    }).map(net => {
        const verAndroid = getVar('VER_ANDROID_' + net.key) || net.defaultVersionAndroid;
        const verIos = getVar('VER_IOS_' + net.key) || net.defaultVersionIos;
        return { ...net, verAndroid, verIos };
    });

    // =================================================================
    // ANDROID
    // =================================================================
    if (context.opts.platforms.includes('android')) {
        const platformRoot = path.join(projectRoot, 'platforms/android');
        const gradleFile = path.join(platformRoot, 'app/build-extras.gradle');
        const manifestFile = path.join(platformRoot, 'app/src/main/AndroidManifest.xml');

        let gradleContent = "// Auto-generated by AdMob Mediation Suite. DO NOT EDIT.\n";

        const repos = enabledNetworks
            .filter(net => net.mavenRepo)
            .map(net => net.mavenRepo);

        if (repos.length > 0) {
            gradleContent += "repositories {\n";
            repos.forEach(repo => {
                gradleContent += `    maven { url "${repo}" }\n`;
            });
            gradleContent += "}\n";
        }

        gradleContent += "dependencies {\n";
        enabledNetworks.forEach(net => {
            gradleContent += `    implementation 'com.google.ads.mediation:${net.artifact}:${net.verAndroid}'\n`;
            console.log(`Android: Injecting ${net.name} Adapter (${net.verAndroid})`);
        });
        gradleContent += "}\n";

        fs.writeFileSync(gradleFile, gradleContent, 'utf-8');

        if (fs.existsSync(manifestFile)) {
            const manifestRaw = fs.readFileSync(manifestFile).toString();
            const manifestTree = et.parse(manifestRaw);
            const root = manifestTree.getroot();
            const appNode = root.find('application');

            let manifestChanged = false;

            enabledNetworks.forEach(net => {
                if (!net.manifestMeta || !appNode) return;
                const metaValue = getVar(net.manifestMeta.varKey);
                if (!metaValue) return;

                const existing = appNode.findall(`./meta-data[@android:name='${net.manifestMeta.name}']`);
                existing.forEach(node => appNode.remove(node));

                let meta = new et.Element('meta-data');
                meta.set('android:name', net.manifestMeta.name);
                meta.set('android:value', metaValue);
                appNode.append(meta);
                manifestChanged = true;
                console.log(`Android: ${net.name} Key Injected to Manifest`);
            });

            if (manifestChanged) {
                fs.writeFileSync(manifestFile, manifestTree.write({ indent: 4 }), 'utf-8');
            }
        }
    }

    // =================================================================
    // iOS
    // =================================================================
    if (context.opts.platforms.includes('ios')) {
        const platformRoot = path.join(projectRoot, 'platforms/ios');
        const directories = fs.readdirSync(platformRoot).filter(file => fs.statSync(path.join(platformRoot, file)).isDirectory());
        const projName = directories.find(dir => !dir.endsWith('.xcassets') && !dir.endsWith('.xcodeproj') && dir !== 'cordova' && dir !== 'pods');

        const podfile = path.join(platformRoot, 'Podfile');
        const plistFile = path.join(platformRoot, projName, `${projName}-Info.plist`);

        if (fs.existsSync(podfile)) {
            let podContent = fs.readFileSync(podfile, 'utf-8');
            const startMarker = "# AdMob-MEDIATION-START";
            const endMarker = "# AdMob-MEDIATION-END";

            const regex = new RegExp(`${startMarker}[\\s\\S]*?${endMarker}`, 'g');
            podContent = podContent.replace(regex, '');

            let newPods = `\n${startMarker}\n`;
            enabledNetworks.forEach(net => {
                newPods += `pod '${net.pod}', '${net.verIos}'\n`;
            });
            newPods += `${endMarker}\n`;

            podContent += newPods;
            fs.writeFileSync(podfile, podContent, 'utf-8');
            console.log("iOS: Podfile updated.");
        }

        if (fs.existsSync(plistFile)) {
            let plistContent = fs.readFileSync(plistFile, 'utf-8');

            enabledNetworks.forEach(net => {
                if (!net.plistKey) return;
                const keyValue = getVar(net.manifestMeta ? net.manifestMeta.varKey : '');
                if (!keyValue) return;

                const removeRegex = new RegExp(`<key>${net.plistKey}<\\/key>\\s*<string>.*?<\\/string>`, 'g');
                plistContent = plistContent.replace(removeRegex, '');

                const insertion = `\n    <key>${net.plistKey}</key>\n    <string>${keyValue}</string>`;
                const lastDictIndex = plistContent.lastIndexOf('</dict>');
                if (lastDictIndex !== -1) {
                    plistContent = plistContent.substring(0, lastDictIndex) + insertion + plistContent.substring(lastDictIndex);
                    console.log(`iOS: ${net.name} Key Injected to Info.plist`);
                }
            });

            fs.writeFileSync(plistFile, plistContent, 'utf-8');
        }
    }

    return Promise.resolve();
};
